refactor: Container rename 2
FlowFuse/helm pull request #274
Opened 2024-01-11 09:18 UTC by hardillb

## Description

NOT to be merged before #272 

## Related Issue(s)

part of FlowFuse/admin#212

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-01-16 09:16 UTC, knolleary requested changes
FlowFuse org on dockerhub has its own set of credentials

2024-02-16 11:27 UTC, ppawlowski approved these changes

2024-02-19 09:38 UTC, hardillb commented
@knolleary when you get a second

2024-02-19 09:42 UTC, knolleary approved these changes

2024-02-19 09:44 UTC, merged